---
# This Docker composition file is used to build and test the container

name: postfix-docker

secrets:
  fullchain_pem:
    file: ./src/secrets/fullchain.pem
  privkey_pem:
    file: ./src/secrets/privkey.pem
  users_txt:
    file: ./src/secrets/users.txt


services:
  postfix:
    build:
      context: .
      dockerfile: Dockerfile
    image: cisagov/postfix
    init: true
    restart: always
    environment:
      - PRIMARY_DOMAIN=${PRIMARY_DOMAIN}
      - RELAY_IP=${RELAY_IP:-172.16.202.1/32}
    networks:
      front:
        ipv4_address: 172.16.202.2
    ports:
      - target: "25"
        published: ${SMTP_PORT:-1025}
        protocol: tcp
        mode: host
      - target: "587"
        published: ${STARTTLS_PORT:-1587}
        protocol: tcp
        mode: host
      - target: "993"
        published: ${IMAP_PORT:-1993}
        protocol: tcp
        mode: host
    secrets:
      - source: fullchain_pem
        target: fullchain.pem
      - source: privkey_pem
        target: privkey.pem
      - source: users_txt
        target: users.txt
    volumes:
      - postfix-etc:/etc
      - postfix-home:/home
      - postfix-root:/root
      - postfix-var:/var

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24
volumes:
  postfix-etc:
  postfix-home:
  postfix-root:
  postfix-var:
