dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.1

auth_mechanisms = plain login
mail_driver = mbox
mail_inbox_path = /var/mail/%{user}
mail_path = ~/mail
mail_privileged_group = mail
protocols = imap



userdb passwd {
  driver = passwd
}
passdb pam {
  driver = pam
  pam_service_name = %{protocol}
}
protocol imap {
}

namespace inbox {
  inbox = yes
  separator = /
  
  mailbox Trash {
    auto = create
    special_use = \Trash
  }
  mailbox Sent {
    auto = create
    special_use = \Sent
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}
ssl=required
ssl_server {
  cert_file = /run/secrets/fullchain.pem
  key_file = /run/secrets/privkey.pem
}

